  
sudo: required
services:
  - docker

before_install:
  - docker build -t adnanmayo/docker-react -f Dockerfile.dev .

script:
  - docker run adnanmayo/docker-react CI=true npm run test -- --coverage